### ISSUE TITLE
Adds demo

### ISSUE THREAD

**Issue by godu** [benoitvallon/react-native-nw-react-calculator#16]
Please, add demo to show the running application.

After https://github.com/benoitvallon/react-native-nw-react-calculator/pull/15 's merge,

```shell
npm run build
cd dist
git init && git add . && git commit -m "Pages"
git remote add github git@github.com:benoitvallon/react-native-nw-react-calculator.git
git push -f github master:gh-pages
```

I tried it on my side.
[my demo](http://godu.github.io/react-native-nw-react-calculator)
[my branch](https://github.com/godu/react-native-nw-react-calculator/tree/gh-pages)

**Comment by benoitvallon** [comment]
Thanks for your issue and request for a demo.

The demo is now available at http://benoitvallon.github.io/react-native-nw-react-calculator
